### ISSUE TITLE
Why these lines in package.json?

### ISSUE THREAD

**Issue by zatomant** [swcolegrove/css-override-web-extension#4]
"devDependencies": {
    "eslint": "^6.3.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.18.2"
  },

**Comment by djragsdale** [comment]
@zatomant those are devDependencies to check for lint within the code. If you install locally, you can run `npm run lint` to check for lint.

**Comment by ri0t** [comment]
And while "eslint-config-airbnb-base" may look fishy AF, it is very legit. It's AirBNB's [pretty nice configuration](https://github.com/airbnb/javascript) for the linter - or "guidelines on how to write javascript".

**Comment by zatomant** [comment]
"look fishy AF, it is very legit"

Okay.
